# Generated by Django 5.2.1 on 2025-06-09 06:40

import books.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_profile_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=5000, null=True)),
                ('author', models.CharField(blank=True, max_length=1000, null=True)),
                ('genre', models.CharField(blank=True, max_length=1000, null=True)),
                ('publicationDate', models.DateField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=1000, null=True)),
                ('nopage', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to=books.models.upload_to)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
