# Generated by Django 5.2.1 on 2025-06-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='nopage',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
